// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx5DslY3sSt2fQpMKzLwcT_ekz9r_R8xM',
    appId: '1:53454204778:android:d4d0160e7e6992009f3f13',
    messagingSenderId: '53454204778',
    projectId: 'consorcio-d9a72',
    storageBucket: 'consorcio-d9a72.appspot.com',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyADsJbkxRooP9rqebicU3NJKGs_EewMBMc",
    authDomain: "consorcio-d9a72.firebaseapp.com",
    projectId: "consorcio-d9a72",
    storageBucket: "consorcio-d9a72.appspot.com",
    messagingSenderId: "53454204778",
    appId: "1:53454204778:web:14791861a9d75f889f3f13",
    measurementId: "G-DHERSM01Y6"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA13_tvDXb2HQUDRnwhwnR2e6r6b5BEqAQ',
    appId: '1:53454204778:ios:cc1758bb01ed22ee9f3f13',
    messagingSenderId: '53454204778',
    projectId: 'consorcio-d9a72',
    storageBucket: 'consorcio-d9a72.appspot.com',
    iosClientId: '53454204778-p014sf77pt84q6qi09vtpj4lt9ch01i6.apps.googleusercontent.com',
    iosBundleId: 'br.unitins.pub',
  );
}
